/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedPublicacoesRouteImport } from './routes/_authenticated/publicacoes'
import { Route as AuthenticatedPropostasRouteImport } from './routes/_authenticated/propostas'
import { Route as AuthenticatedPecasRouteImport } from './routes/_authenticated/pecas'
import { Route as AuthenticatedParecerTecnicoRouteImport } from './routes/_authenticated/parecer-tecnico'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBoasVindasRouteImport } from './routes/_authenticated/boas-vindas'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAssistenciasRouteImport } from './routes/_authenticated/assistencias'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedPlataformaIndexRouteImport } from './routes/_authenticated/plataforma.index'
import { Route as AuthenticatedAssistenciasIndexRouteImport } from './routes/_authenticated/assistencias.index'
import { Route as ApiToolsTranscribeRouteImport } from './routes/api/tools/transcribe'
import { Route as ApiToolsTableRouteImport } from './routes/api/tools/table'
import { Route as ApiToolsPresentationRouteImport } from './routes/api/tools/presentation'
import { Route as ApiToolsPetitionRouteImport } from './routes/api/tools/petition'
import { Route as ApiToolsPdfRouteImport } from './routes/api/tools/pdf'
import { Route as AuthenticatedConfiguracoesOauthRouteImport } from './routes/_authenticated/configuracoes.oauth'
import { Route as AuthenticatedConfiguracoesEscritorioRouteImport } from './routes/_authenticated/configuracoes.escritorio'
import { Route as AuthenticatedAssistenciasNovaRouteImport } from './routes/_authenticated/assistencias.nova'
import { Route as AuthenticatedAssistenciasLoteRouteImport } from './routes/_authenticated/assistencias.lote'
import { Route as AuthenticatedAssistenciasCaseIdRouteImport } from './routes/_authenticated/assistencias.$caseId'
import { Route as AuthenticatedPlataformaUsuariosIndexRouteImport } from './routes/_authenticated/plataforma.usuarios.index'
import { Route as AuthenticatedPlataformaCredenciaisIndexRouteImport } from './routes/_authenticated/plataforma.credenciais.index'
import { Route as AuthenticatedPlataformaClientesIndexRouteImport } from './routes/_authenticated/plataforma.clientes.index'
import { Route as AuthenticatedPlataformaAuditoriaIndexRouteImport } from './routes/_authenticated/plataforma.auditoria.index'
import { Route as ApiPublicOutlookCallbackRouteImport } from './routes/api/public/outlook/callback'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'
import { Route as AuthenticatedPlataformaClientesIdRouteImport } from './routes/_authenticated/plataforma.clientes.$id'
import { Route as AuthenticatedAssistenciasCaseIdChatRouteImport } from './routes/_authenticated/assistencias.$caseId.chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPublicacoesRoute =
  AuthenticatedPublicacoesRouteImport.update({
    id: '/publicacoes',
    path: '/publicacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropostasRoute = AuthenticatedPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPecasRoute = AuthenticatedPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParecerTecnicoRoute =
  AuthenticatedParecerTecnicoRouteImport.update({
    id: '/parecer-tecnico',
    path: '/parecer-tecnico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBoasVindasRoute = AuthenticatedBoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistenciasRoute =
  AuthenticatedAssistenciasRouteImport.update({
    id: '/assistencias',
    path: '/assistencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlataformaIndexRoute =
  AuthenticatedPlataformaIndexRouteImport.update({
    id: '/plataforma/',
    path: '/plataforma/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssistenciasIndexRoute =
  AuthenticatedAssistenciasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistenciasRoute,
  } as any)
const ApiToolsTranscribeRoute = ApiToolsTranscribeRouteImport.update({
  id: '/api/tools/transcribe',
  path: '/api/tools/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsTableRoute = ApiToolsTableRouteImport.update({
  id: '/api/tools/table',
  path: '/api/tools/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsPresentationRoute = ApiToolsPresentationRouteImport.update({
  id: '/api/tools/presentation',
  path: '/api/tools/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsPetitionRoute = ApiToolsPetitionRouteImport.update({
  id: '/api/tools/petition',
  path: '/api/tools/petition',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsPdfRoute = ApiToolsPdfRouteImport.update({
  id: '/api/tools/pdf',
  path: '/api/tools/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesOauthRoute =
  AuthenticatedConfiguracoesOauthRouteImport.update({
    id: '/oauth',
    path: '/oauth',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesEscritorioRoute =
  AuthenticatedConfiguracoesEscritorioRouteImport.update({
    id: '/escritorio',
    path: '/escritorio',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedAssistenciasNovaRoute =
  AuthenticatedAssistenciasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedAssistenciasRoute,
  } as any)
const AuthenticatedAssistenciasLoteRoute =
  AuthenticatedAssistenciasLoteRouteImport.update({
    id: '/lote',
    path: '/lote',
    getParentRoute: () => AuthenticatedAssistenciasRoute,
  } as any)
const AuthenticatedAssistenciasCaseIdRoute =
  AuthenticatedAssistenciasCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AuthenticatedAssistenciasRoute,
  } as any)
const AuthenticatedPlataformaUsuariosIndexRoute =
  AuthenticatedPlataformaUsuariosIndexRouteImport.update({
    id: '/plataforma/usuarios/',
    path: '/plataforma/usuarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlataformaCredenciaisIndexRoute =
  AuthenticatedPlataformaCredenciaisIndexRouteImport.update({
    id: '/plataforma/credenciais/',
    path: '/plataforma/credenciais/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlataformaClientesIndexRoute =
  AuthenticatedPlataformaClientesIndexRouteImport.update({
    id: '/plataforma/clientes/',
    path: '/plataforma/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlataformaAuditoriaIndexRoute =
  AuthenticatedPlataformaAuditoriaIndexRouteImport.update({
    id: '/plataforma/auditoria/',
    path: '/plataforma/auditoria/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicOutlookCallbackRoute =
  ApiPublicOutlookCallbackRouteImport.update({
    id: '/api/public/outlook/callback',
    path: '/api/public/outlook/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlataformaClientesIdRoute =
  AuthenticatedPlataformaClientesIdRouteImport.update({
    id: '/plataforma/clientes/$id',
    path: '/plataforma/clientes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssistenciasCaseIdChatRoute =
  AuthenticatedAssistenciasCaseIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedAssistenciasCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assistencias': typeof AuthenticatedAssistenciasRouteWithChildren
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/conversas': typeof AuthenticatedConversasRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/parecer-tecnico': typeof AuthenticatedParecerTecnicoRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/publicacoes': typeof AuthenticatedPublicacoesRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/invite/$token': typeof InviteTokenRoute
  '/assistencias/$caseId': typeof AuthenticatedAssistenciasCaseIdRouteWithChildren
  '/assistencias/lote': typeof AuthenticatedAssistenciasLoteRoute
  '/assistencias/nova': typeof AuthenticatedAssistenciasNovaRoute
  '/configuracoes/escritorio': typeof AuthenticatedConfiguracoesEscritorioRoute
  '/configuracoes/oauth': typeof AuthenticatedConfiguracoesOauthRoute
  '/api/tools/pdf': typeof ApiToolsPdfRoute
  '/api/tools/petition': typeof ApiToolsPetitionRoute
  '/api/tools/presentation': typeof ApiToolsPresentationRoute
  '/api/tools/table': typeof ApiToolsTableRoute
  '/api/tools/transcribe': typeof ApiToolsTranscribeRoute
  '/assistencias/': typeof AuthenticatedAssistenciasIndexRoute
  '/plataforma/': typeof AuthenticatedPlataformaIndexRoute
  '/assistencias/$caseId/chat': typeof AuthenticatedAssistenciasCaseIdChatRoute
  '/plataforma/clientes/$id': typeof AuthenticatedPlataformaClientesIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/outlook/callback': typeof ApiPublicOutlookCallbackRoute
  '/plataforma/auditoria/': typeof AuthenticatedPlataformaAuditoriaIndexRoute
  '/plataforma/clientes/': typeof AuthenticatedPlataformaClientesIndexRoute
  '/plataforma/credenciais/': typeof AuthenticatedPlataformaCredenciaisIndexRoute
  '/plataforma/usuarios/': typeof AuthenticatedPlataformaUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/conversas': typeof AuthenticatedConversasRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/parecer-tecnico': typeof AuthenticatedParecerTecnicoRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/publicacoes': typeof AuthenticatedPublicacoesRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/invite/$token': typeof InviteTokenRoute
  '/assistencias/$caseId': typeof AuthenticatedAssistenciasCaseIdRouteWithChildren
  '/assistencias/lote': typeof AuthenticatedAssistenciasLoteRoute
  '/assistencias/nova': typeof AuthenticatedAssistenciasNovaRoute
  '/configuracoes/escritorio': typeof AuthenticatedConfiguracoesEscritorioRoute
  '/configuracoes/oauth': typeof AuthenticatedConfiguracoesOauthRoute
  '/api/tools/pdf': typeof ApiToolsPdfRoute
  '/api/tools/petition': typeof ApiToolsPetitionRoute
  '/api/tools/presentation': typeof ApiToolsPresentationRoute
  '/api/tools/table': typeof ApiToolsTableRoute
  '/api/tools/transcribe': typeof ApiToolsTranscribeRoute
  '/assistencias': typeof AuthenticatedAssistenciasIndexRoute
  '/plataforma': typeof AuthenticatedPlataformaIndexRoute
  '/assistencias/$caseId/chat': typeof AuthenticatedAssistenciasCaseIdChatRoute
  '/plataforma/clientes/$id': typeof AuthenticatedPlataformaClientesIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/outlook/callback': typeof ApiPublicOutlookCallbackRoute
  '/plataforma/auditoria': typeof AuthenticatedPlataformaAuditoriaIndexRoute
  '/plataforma/clientes': typeof AuthenticatedPlataformaClientesIndexRoute
  '/plataforma/credenciais': typeof AuthenticatedPlataformaCredenciaisIndexRoute
  '/plataforma/usuarios': typeof AuthenticatedPlataformaUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/assistencias': typeof AuthenticatedAssistenciasRouteWithChildren
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/parecer-tecnico': typeof AuthenticatedParecerTecnicoRoute
  '/_authenticated/pecas': typeof AuthenticatedPecasRoute
  '/_authenticated/propostas': typeof AuthenticatedPropostasRoute
  '/_authenticated/publicacoes': typeof AuthenticatedPublicacoesRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/assistencias/$caseId': typeof AuthenticatedAssistenciasCaseIdRouteWithChildren
  '/_authenticated/assistencias/lote': typeof AuthenticatedAssistenciasLoteRoute
  '/_authenticated/assistencias/nova': typeof AuthenticatedAssistenciasNovaRoute
  '/_authenticated/configuracoes/escritorio': typeof AuthenticatedConfiguracoesEscritorioRoute
  '/_authenticated/configuracoes/oauth': typeof AuthenticatedConfiguracoesOauthRoute
  '/api/tools/pdf': typeof ApiToolsPdfRoute
  '/api/tools/petition': typeof ApiToolsPetitionRoute
  '/api/tools/presentation': typeof ApiToolsPresentationRoute
  '/api/tools/table': typeof ApiToolsTableRoute
  '/api/tools/transcribe': typeof ApiToolsTranscribeRoute
  '/_authenticated/assistencias/': typeof AuthenticatedAssistenciasIndexRoute
  '/_authenticated/plataforma/': typeof AuthenticatedPlataformaIndexRoute
  '/_authenticated/assistencias/$caseId/chat': typeof AuthenticatedAssistenciasCaseIdChatRoute
  '/_authenticated/plataforma/clientes/$id': typeof AuthenticatedPlataformaClientesIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/outlook/callback': typeof ApiPublicOutlookCallbackRoute
  '/_authenticated/plataforma/auditoria/': typeof AuthenticatedPlataformaAuditoriaIndexRoute
  '/_authenticated/plataforma/clientes/': typeof AuthenticatedPlataformaClientesIndexRoute
  '/_authenticated/plataforma/credenciais/': typeof AuthenticatedPlataformaCredenciaisIndexRoute
  '/_authenticated/plataforma/usuarios/': typeof AuthenticatedPlataformaUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/assistencias'
    | '/assistente'
    | '/boas-vindas'
    | '/configuracoes'
    | '/conversas'
    | '/documentos'
    | '/integracoes'
    | '/marketing'
    | '/notificacoes'
    | '/painel'
    | '/parecer-tecnico'
    | '/pecas'
    | '/propostas'
    | '/publicacoes'
    | '/tarefas'
    | '/invite/$token'
    | '/assistencias/$caseId'
    | '/assistencias/lote'
    | '/assistencias/nova'
    | '/configuracoes/escritorio'
    | '/configuracoes/oauth'
    | '/api/tools/pdf'
    | '/api/tools/petition'
    | '/api/tools/presentation'
    | '/api/tools/table'
    | '/api/tools/transcribe'
    | '/assistencias/'
    | '/plataforma/'
    | '/assistencias/$caseId/chat'
    | '/plataforma/clientes/$id'
    | '/api/public/google/callback'
    | '/api/public/outlook/callback'
    | '/plataforma/auditoria/'
    | '/plataforma/clientes/'
    | '/plataforma/credenciais/'
    | '/plataforma/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/assistente'
    | '/boas-vindas'
    | '/configuracoes'
    | '/conversas'
    | '/documentos'
    | '/integracoes'
    | '/marketing'
    | '/notificacoes'
    | '/painel'
    | '/parecer-tecnico'
    | '/pecas'
    | '/propostas'
    | '/publicacoes'
    | '/tarefas'
    | '/invite/$token'
    | '/assistencias/$caseId'
    | '/assistencias/lote'
    | '/assistencias/nova'
    | '/configuracoes/escritorio'
    | '/configuracoes/oauth'
    | '/api/tools/pdf'
    | '/api/tools/petition'
    | '/api/tools/presentation'
    | '/api/tools/table'
    | '/api/tools/transcribe'
    | '/assistencias'
    | '/plataforma'
    | '/assistencias/$caseId/chat'
    | '/plataforma/clientes/$id'
    | '/api/public/google/callback'
    | '/api/public/outlook/callback'
    | '/plataforma/auditoria'
    | '/plataforma/clientes'
    | '/plataforma/credenciais'
    | '/plataforma/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/assistencias'
    | '/_authenticated/assistente'
    | '/_authenticated/boas-vindas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conversas'
    | '/_authenticated/documentos'
    | '/_authenticated/integracoes'
    | '/_authenticated/marketing'
    | '/_authenticated/notificacoes'
    | '/_authenticated/painel'
    | '/_authenticated/parecer-tecnico'
    | '/_authenticated/pecas'
    | '/_authenticated/propostas'
    | '/_authenticated/publicacoes'
    | '/_authenticated/tarefas'
    | '/invite/$token'
    | '/_authenticated/assistencias/$caseId'
    | '/_authenticated/assistencias/lote'
    | '/_authenticated/assistencias/nova'
    | '/_authenticated/configuracoes/escritorio'
    | '/_authenticated/configuracoes/oauth'
    | '/api/tools/pdf'
    | '/api/tools/petition'
    | '/api/tools/presentation'
    | '/api/tools/table'
    | '/api/tools/transcribe'
    | '/_authenticated/assistencias/'
    | '/_authenticated/plataforma/'
    | '/_authenticated/assistencias/$caseId/chat'
    | '/_authenticated/plataforma/clientes/$id'
    | '/api/public/google/callback'
    | '/api/public/outlook/callback'
    | '/_authenticated/plataforma/auditoria/'
    | '/_authenticated/plataforma/clientes/'
    | '/_authenticated/plataforma/credenciais/'
    | '/_authenticated/plataforma/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiToolsPdfRoute: typeof ApiToolsPdfRoute
  ApiToolsPetitionRoute: typeof ApiToolsPetitionRoute
  ApiToolsPresentationRoute: typeof ApiToolsPresentationRoute
  ApiToolsTableRoute: typeof ApiToolsTableRoute
  ApiToolsTranscribeRoute: typeof ApiToolsTranscribeRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicOutlookCallbackRoute: typeof ApiPublicOutlookCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/publicacoes': {
      id: '/_authenticated/publicacoes'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof AuthenticatedPublicacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/propostas': {
      id: '/_authenticated/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AuthenticatedPropostasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pecas': {
      id: '/_authenticated/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof AuthenticatedPecasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parecer-tecnico': {
      id: '/_authenticated/parecer-tecnico'
      path: '/parecer-tecnico'
      fullPath: '/parecer-tecnico'
      preLoaderRoute: typeof AuthenticatedParecerTecnicoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/boas-vindas': {
      id: '/_authenticated/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof AuthenticatedBoasVindasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistencias': {
      id: '/_authenticated/assistencias'
      path: '/assistencias'
      fullPath: '/assistencias'
      preLoaderRoute: typeof AuthenticatedAssistenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plataforma/': {
      id: '/_authenticated/plataforma/'
      path: '/plataforma'
      fullPath: '/plataforma/'
      preLoaderRoute: typeof AuthenticatedPlataformaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistencias/': {
      id: '/_authenticated/assistencias/'
      path: '/'
      fullPath: '/assistencias/'
      preLoaderRoute: typeof AuthenticatedAssistenciasIndexRouteImport
      parentRoute: typeof AuthenticatedAssistenciasRoute
    }
    '/api/tools/transcribe': {
      id: '/api/tools/transcribe'
      path: '/api/tools/transcribe'
      fullPath: '/api/tools/transcribe'
      preLoaderRoute: typeof ApiToolsTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/table': {
      id: '/api/tools/table'
      path: '/api/tools/table'
      fullPath: '/api/tools/table'
      preLoaderRoute: typeof ApiToolsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/presentation': {
      id: '/api/tools/presentation'
      path: '/api/tools/presentation'
      fullPath: '/api/tools/presentation'
      preLoaderRoute: typeof ApiToolsPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/petition': {
      id: '/api/tools/petition'
      path: '/api/tools/petition'
      fullPath: '/api/tools/petition'
      preLoaderRoute: typeof ApiToolsPetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/pdf': {
      id: '/api/tools/pdf'
      path: '/api/tools/pdf'
      fullPath: '/api/tools/pdf'
      preLoaderRoute: typeof ApiToolsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes/oauth': {
      id: '/_authenticated/configuracoes/oauth'
      path: '/oauth'
      fullPath: '/configuracoes/oauth'
      preLoaderRoute: typeof AuthenticatedConfiguracoesOauthRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/escritorio': {
      id: '/_authenticated/configuracoes/escritorio'
      path: '/escritorio'
      fullPath: '/configuracoes/escritorio'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEscritorioRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/assistencias/nova': {
      id: '/_authenticated/assistencias/nova'
      path: '/nova'
      fullPath: '/assistencias/nova'
      preLoaderRoute: typeof AuthenticatedAssistenciasNovaRouteImport
      parentRoute: typeof AuthenticatedAssistenciasRoute
    }
    '/_authenticated/assistencias/lote': {
      id: '/_authenticated/assistencias/lote'
      path: '/lote'
      fullPath: '/assistencias/lote'
      preLoaderRoute: typeof AuthenticatedAssistenciasLoteRouteImport
      parentRoute: typeof AuthenticatedAssistenciasRoute
    }
    '/_authenticated/assistencias/$caseId': {
      id: '/_authenticated/assistencias/$caseId'
      path: '/$caseId'
      fullPath: '/assistencias/$caseId'
      preLoaderRoute: typeof AuthenticatedAssistenciasCaseIdRouteImport
      parentRoute: typeof AuthenticatedAssistenciasRoute
    }
    '/_authenticated/plataforma/usuarios/': {
      id: '/_authenticated/plataforma/usuarios/'
      path: '/plataforma/usuarios'
      fullPath: '/plataforma/usuarios/'
      preLoaderRoute: typeof AuthenticatedPlataformaUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plataforma/credenciais/': {
      id: '/_authenticated/plataforma/credenciais/'
      path: '/plataforma/credenciais'
      fullPath: '/plataforma/credenciais/'
      preLoaderRoute: typeof AuthenticatedPlataformaCredenciaisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plataforma/clientes/': {
      id: '/_authenticated/plataforma/clientes/'
      path: '/plataforma/clientes'
      fullPath: '/plataforma/clientes/'
      preLoaderRoute: typeof AuthenticatedPlataformaClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plataforma/auditoria/': {
      id: '/_authenticated/plataforma/auditoria/'
      path: '/plataforma/auditoria'
      fullPath: '/plataforma/auditoria/'
      preLoaderRoute: typeof AuthenticatedPlataformaAuditoriaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/outlook/callback': {
      id: '/api/public/outlook/callback'
      path: '/api/public/outlook/callback'
      fullPath: '/api/public/outlook/callback'
      preLoaderRoute: typeof ApiPublicOutlookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plataforma/clientes/$id': {
      id: '/_authenticated/plataforma/clientes/$id'
      path: '/plataforma/clientes/$id'
      fullPath: '/plataforma/clientes/$id'
      preLoaderRoute: typeof AuthenticatedPlataformaClientesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistencias/$caseId/chat': {
      id: '/_authenticated/assistencias/$caseId/chat'
      path: '/chat'
      fullPath: '/assistencias/$caseId/chat'
      preLoaderRoute: typeof AuthenticatedAssistenciasCaseIdChatRouteImport
      parentRoute: typeof AuthenticatedAssistenciasCaseIdRoute
    }
  }
}

interface AuthenticatedAssistenciasCaseIdRouteChildren {
  AuthenticatedAssistenciasCaseIdChatRoute: typeof AuthenticatedAssistenciasCaseIdChatRoute
}

const AuthenticatedAssistenciasCaseIdRouteChildren: AuthenticatedAssistenciasCaseIdRouteChildren =
  {
    AuthenticatedAssistenciasCaseIdChatRoute:
      AuthenticatedAssistenciasCaseIdChatRoute,
  }

const AuthenticatedAssistenciasCaseIdRouteWithChildren =
  AuthenticatedAssistenciasCaseIdRoute._addFileChildren(
    AuthenticatedAssistenciasCaseIdRouteChildren,
  )

interface AuthenticatedAssistenciasRouteChildren {
  AuthenticatedAssistenciasCaseIdRoute: typeof AuthenticatedAssistenciasCaseIdRouteWithChildren
  AuthenticatedAssistenciasLoteRoute: typeof AuthenticatedAssistenciasLoteRoute
  AuthenticatedAssistenciasNovaRoute: typeof AuthenticatedAssistenciasNovaRoute
  AuthenticatedAssistenciasIndexRoute: typeof AuthenticatedAssistenciasIndexRoute
}

const AuthenticatedAssistenciasRouteChildren: AuthenticatedAssistenciasRouteChildren =
  {
    AuthenticatedAssistenciasCaseIdRoute:
      AuthenticatedAssistenciasCaseIdRouteWithChildren,
    AuthenticatedAssistenciasLoteRoute: AuthenticatedAssistenciasLoteRoute,
    AuthenticatedAssistenciasNovaRoute: AuthenticatedAssistenciasNovaRoute,
    AuthenticatedAssistenciasIndexRoute: AuthenticatedAssistenciasIndexRoute,
  }

const AuthenticatedAssistenciasRouteWithChildren =
  AuthenticatedAssistenciasRoute._addFileChildren(
    AuthenticatedAssistenciasRouteChildren,
  )

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesEscritorioRoute: typeof AuthenticatedConfiguracoesEscritorioRoute
  AuthenticatedConfiguracoesOauthRoute: typeof AuthenticatedConfiguracoesOauthRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesEscritorioRoute:
      AuthenticatedConfiguracoesEscritorioRoute,
    AuthenticatedConfiguracoesOauthRoute: AuthenticatedConfiguracoesOauthRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAssistenciasRoute: typeof AuthenticatedAssistenciasRouteWithChildren
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedBoasVindasRoute: typeof AuthenticatedBoasVindasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedParecerTecnicoRoute: typeof AuthenticatedParecerTecnicoRoute
  AuthenticatedPecasRoute: typeof AuthenticatedPecasRoute
  AuthenticatedPropostasRoute: typeof AuthenticatedPropostasRoute
  AuthenticatedPublicacoesRoute: typeof AuthenticatedPublicacoesRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedPlataformaIndexRoute: typeof AuthenticatedPlataformaIndexRoute
  AuthenticatedPlataformaClientesIdRoute: typeof AuthenticatedPlataformaClientesIdRoute
  AuthenticatedPlataformaAuditoriaIndexRoute: typeof AuthenticatedPlataformaAuditoriaIndexRoute
  AuthenticatedPlataformaClientesIndexRoute: typeof AuthenticatedPlataformaClientesIndexRoute
  AuthenticatedPlataformaCredenciaisIndexRoute: typeof AuthenticatedPlataformaCredenciaisIndexRoute
  AuthenticatedPlataformaUsuariosIndexRoute: typeof AuthenticatedPlataformaUsuariosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAssistenciasRoute: AuthenticatedAssistenciasRouteWithChildren,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedBoasVindasRoute: AuthenticatedBoasVindasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedParecerTecnicoRoute: AuthenticatedParecerTecnicoRoute,
  AuthenticatedPecasRoute: AuthenticatedPecasRoute,
  AuthenticatedPropostasRoute: AuthenticatedPropostasRoute,
  AuthenticatedPublicacoesRoute: AuthenticatedPublicacoesRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedPlataformaIndexRoute: AuthenticatedPlataformaIndexRoute,
  AuthenticatedPlataformaClientesIdRoute:
    AuthenticatedPlataformaClientesIdRoute,
  AuthenticatedPlataformaAuditoriaIndexRoute:
    AuthenticatedPlataformaAuditoriaIndexRoute,
  AuthenticatedPlataformaClientesIndexRoute:
    AuthenticatedPlataformaClientesIndexRoute,
  AuthenticatedPlataformaCredenciaisIndexRoute:
    AuthenticatedPlataformaCredenciaisIndexRoute,
  AuthenticatedPlataformaUsuariosIndexRoute:
    AuthenticatedPlataformaUsuariosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiToolsPdfRoute: ApiToolsPdfRoute,
  ApiToolsPetitionRoute: ApiToolsPetitionRoute,
  ApiToolsPresentationRoute: ApiToolsPresentationRoute,
  ApiToolsTableRoute: ApiToolsTableRoute,
  ApiToolsTranscribeRoute: ApiToolsTranscribeRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicOutlookCallbackRoute: ApiPublicOutlookCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
